---
- src: https://github.com/OULibraries/ansible-role-centos7
  version: v2016-06-10.0
  name: OULibraries.centos7

- src: https://github.com/OULibraries/ansible-role-docker-host
  version: v2016-06-21.0
  name: OULibraries.docker-host

- src: https://github.com/OULibraries/ansible-role-users
  version: v2016-06-10.0
  name: OULibraries.users
